# This is a configuration file that to run REVISE algorithm on the MNIST dataset.
data_dir : "/teamspace/studios/this_studio/CF-Robustness-Benchmark/data"
# data_dir : "data"

# configure the dataset 
data: {
  name : "dermamnist",
  class_name : 'MedMNISTDataset',
  classes: ['basal cell carcinoma', 'benign keratosis-like lesions', 'melanoma', 'melanocytic nevi' ], 
  num_classes: 4,
  img_size: 64,
  download: True,
  undersample_flag: True, # if the dataset is unbalanced, set to True to undersample the majority class in binary setting
  channels_first: True, # if True, the input tensor is in (C, H, W) format, otherwise (H, W, C)
  increase_channels: False # increase channels to 3 
}


classifier:
  name: "build_resnet50" # a class name of the predictive model to use
  args:
    pretrained: False
    freeze_backbone: False
    unfreeze_last_n: 0
  lightning_used: False
  # path to the checkpoints
  checkpoints_path: '/teamspace/studios/this_studio/CF-Robustness-Benchmark/notebooks/experiments/dermamnist_classification/multiclass/checkpoints/derma_resnet50_acc=0.74.pth'


batch_size: 64
num_workers: 1
accelerator: "cuda"
devices: 1 # number of devices to use
save_dir: "/teamspace/studios/this_studio/CF-Robustness-Benchmark/cf_output/derma/c3lt_multi"
# "D:/PycharmProjects/CF-Robustness-Benchmark/cf_output/mnist/revise_binary"
