# This is a configuration file that to run REVISE algorithm on the MNIST dataset.
data_dir : "/teamspace/studios/this_studio/CF-Robustness-Benchmark/data"
# data_dir : "data"

# configure the dataset 
data: {
  name : "mnist",
  class_name : 'MNISTDataset',
  classes: [1, 8],
  num_classes: 2,
  img_size: 28,
  download: True,
  undersample_flag: False, # if the dataset is unbalanced, set to True to undersample the majority class in binary setting
  channels_first: True, # if True, the input tensor is in (C, H, W) format, otherwise (H, W, C)
  increase_channels: False # increase channels to 3 
}


# classifier:
#   name: "SimpleCNNtorch" # a class name of the predictive model to use
#   args:
#     input_channels: 1 # number of input channels
#     in_conv_channels: [1, 8, 16] 
#     out_conv_channels: [8, 16, 32]
#     conv_kernels: [7, 5, 3]
#     softmax_flag: True
#   # path to the checkpoints
#   checkpoints_path: "/data/leuven/365/vsc36567/CF-Robustness-Benchmark/notebooks/experiments/mnist_classification/binary/checkpoints/mnist_1_8_epoch=08_val_accuracy=1.00.pth"


classifier:
  name: "CNNtorch" # a class name of the predictive model to use
  args:
    input_channels: 1 # number of input channels
    softmax_flag: True
  # path to the checkpoints
  checkpoints_path: '/teamspace/studios/this_studio/CF-Robustness-Benchmark/notebooks/experiments/mnist_classification/binary/checkpoints/classifier_mnist_1_8.pth'
  # checkpoints_path: '/data/leuven/365/vsc36567/CF-Robustness-Benchmark/notebooks/experiments/mnist_classification/binary/checkpoints/classifier_mnist_1_8.pth'


batch_size: 64
num_workers: 1
accelerator: "cuda"
devices: 1 # number of devices to use
save_dir: "/teamspace/studios/this_studio/CF-Robustness-Benchmark/cf_output/mnist/ldce_binary"
# "D:/PycharmProjects/CF-Robustness-Benchmark/cf_output/mnist/revise_binary"
