# This is a configuration file that to run REVISE algorithm on the MNIST dataset.
data_dir : "/teamspace/studios/this_studio/CF-Robustness-Benchmark/data"

# configure the dataset 
data: {
  name : "dermamnist",
  class_name : 'MedMNISTDataset',
  classes: ['benign keratosis-like lesions', 'melanoma'], 
  num_classes: 2,
  img_size: 64,
  download: True,
  undersample_flag: False, # if the dataset is unbalanced, set to True to undersample the majority class in binary setting
  channels_first: True, # if True, the input tensor is in (C, H, W) format, otherwise (H, W, C)
  increase_channels: False # increase channels to 3 
}


classifier:
  name: "resnet50" # a class name of the predictive model to use
  args:
    input_channels: 3 # number of input channels
    in_conv_channels: [1, 8, 16] 
    out_conv_channels: [8, 16, 32]
    conv_kernels: [7, 5, 3]
    softmax_flag: True
  lightning_used: True
  # path to the checkpoints
  checkpoints_path: "/teamspace/studios/this_studio/CF-Robustness-Benchmark/notebooks/experiments/derma_classification/binary/checkpoints/derma_epoch=30_accuracy=0.87_resnet50.pth"

vae:
  name: "BetaVAEDerma" # name of the model to use
  args:
    latent_dim: 256 # dimension of the latent space
    hidden_dims: [32, 64, 128, 256] # hidden dimensions for the encoder and decoder
    input_channels: 3 # number of input channels (1 for grayscale images)
    beta: 0.05 # weight for the KL divergence term in the loss function
  checkpoints_path: "/teamspace/studios/this_studio/CF-Robustness-Benchmark/notebooks/experiments/dermamnist_vae/binary/checkpoints/dermamnist_benign keratosis-like lesions_melanoma_epoch=96.pth"

revise_hyperparameters:
  lambda: 0.01
  optimizer: "Adam"
  lr: 0.1
  max_iter: 1000
  target_class_ind: [[0, 1]]


batch_size: 64
num_workers: 1
accelerator: "cuda"
devices: 1 # number of devices to use
save_dir: "/teamspace/studios/this_studio/CF-Robustness-Benchmark/cf_output/derma/revise_binary"
#save_dir: "D:/PycharmProjects/CF-Robustness-Benchmark/cf_output/mnist/revise_binary"
