# This is a configuration file for training a classifier on the dermamnist_corrected_224 dataset.
data_dir : "/teamspace/studios/this_studio/CF-Robustness-Benchmark/data"
# "D:/PycharmProjects/CF-Robustness-Benchmark/data"

# configure the dataset 
data: {
  name : "dermamnist",
  class_name : 'MedMNISTDataset',
  classes: ['basal cell carcinoma', 'benign keratosis-like lesions', 'melanoma', 'melanocytic nevi' ], 
  # classes: ['benign keratosis-like lesions', 'melanoma'],

  # CLASS MAPPING  [choose class index to include]
  # '0': 'actinic keratoses and intraepithelial carcinoma',
  # '1': 'basal cell carcinoma',
  # '2': 'benign keratosis-like lesions',
  # '3': 'dermatofibroma',
  # '4': 'melanoma',
  # '5': 'melanocytic nevi',
  # '6': 'vascular lesions'

  num_classes: 4,
  # num_classes: 2,
  img_size: 64,
  download: True,
  undersample_flag: False, # if the dataset is unbalanced, set to True to undersample the majority class in binary setting
  channels_first: True, # if True, the input tensor is in (C, H, W) format, otherwise (H, W, C)
  increase_channels: False # increase channels to 3 
}

classifier:
  name: "resnet50" # a class name of the predictive model to use
  args:
    input_channels: 3 # number of input channels
    pretrained: False
    freeze_backbone: False
    unfreeze_last_n: 0
  # path to the checkpoints
  checkpoints_path: ""
  
loss: 
  name: "CrossEntropyLoss" # loss function to use
  args: {}

optimizer:
  name: "Adam"
  args:
    lr: 0.001
    # lr: 0.0001 # used for the binary classification
    weight_decay: 0.0

lr_scheduler:
  name: "MultiStepLR"
  enable: True
  args:
    milestones: [15, 26]  # 0.5 and 0.75 of 50 epochs
    gamma: 0.1


epochs: 50
batch_size: 16
num_workers: 4
accelerator: "cuda"
devices: 1 # number of devices to use
save_dir: "/teamspace/studios/this_studio/CF-Robustness-Benchmark/notebooks/experiments/dermamnist_classification"
# save_dir: "/teamspace/studios/this_studio/CF-Robustness-Benchmark/notebooks/experiments/dermamnist_classification/binary"
# save_dir: "/data/leuven/365/vsc36567/CF-Robustness-Benchmark/notebooks/experiments/derma_classification"
# "D:/PycharmProjects/CF-Robustness-Benchmark/notebooks/experiments"
checkpoint_path: " " # path to the checkpoint to resume training


