# This is a configuration file for training a classifier on the dermamnist_corrected_224 dataset.
data_dir : "D:/PycharmProjects/Counterfactual-Robustness-Benchmark/data"

# configure the dataset 
data: {
  name : 'MNISTDataset',
  flag : "mnist",
  classes: [1, 7],
  num_classes: 2,
  img_size: 28,
  download: True,
  undersample_flag: False, # if the dataset is unbalanced, set to True to undersample the majority class in binary setting
  channels_first: True, # if True, the input tensor is in (C, H, W) format, otherwise (H, W, C)
  increase_channels: False # increase channels to 3 
}

input_channels: 1 # number of input channels
epochs: 10
batch_size: 64

loss: 
  name: "CrossEntropyLoss" # loss function to use
  args: {}

optimizer:
  name: "Adam"
  args:
    lr: 0.001
    weight_decay: 0.0001

num_workers: 1
accelerator: "cpu"
devices: 1 # number of devices to use
save_dir: " "
checkpoint_path: " " # path to the checkpoint to resume training



